### ISSUE TITLE
WhisperX support

### ISSUE THREAD

**Issue by rbychn** [hayabhay/frogbase#34]
Can you please add [@whisperx](https://github.com/m-bain/whisperX) support for speaker diarization and better timestamping

**Comment by hayabhay** [comment]
This looks super interesting! 

Building a proper web app for the 2.x version so will definitely add this in! Thanks!

**Comment by Ihateyoudattebayo** [comment]
> This looks super interesting!
> 
> Building a proper web app for the 2.x version so will definitely add this in! Thanks!

when are you planning on making the web app

**Comment by menelic** [comment]
Proper web app for v2 sounds great! Any update on this?

**Comment by hayabhay** [comment]
I expect a development version up for testing sometime mid June (might be earlier if I reduce the number of features).

Planning to have a hosted & self-hosted version as well.

Will share a Roadmap when things get done!

**Comment by hayabhay** [comment]
The core backend is packaged out in the [new version](https://github.com/hayabhay/frogbase/discussions/56). Streamlit updates will continue in the near future while a Django application might come into play if there is enough interest.
