### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlalchemy

### ISSUE THREAD

**Issue by gersooonn** [hayabhay/frogbase#54]
Aparece esse erro, quando coloco o link do youtube, ou faço upload do arquivo. 
![image](https://github.com/hayabhay/whisper-ui/assets/128495179/9ae6c85f-a20a-43ff-affd-f97441af586f)

**Comment by hayabhay** [comment]
Closing this since SqlAlchemy has been removed in the [new version](https://github.com/hayabhay/frogbase/discussions/56)
