### ISSUE TITLE
 error at startup : unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by alexschmitt54** [hayabhay/frogbase#65]
Hello,
I have a problem starting the web service
![image](https://github.com/hayabhay/frogbase/assets/139887010/a951f257-3d8a-4d68-a681-4809b5a3224e)
the server is in ubuntu 20.04 LTS and I do not understand where the problem comes from
If you have an idea to help me
Thanks

**Comment by hayabhay** [comment]
Couldn't quite reproduce this. This is likely a problem with when and how the captions file was generated and is most definitely a bug.

Some questions to help me dig deeper:
1. How many files did you have in the library?
2. Can you create a new library and add files in there?

**Comment by alexschmitt54** [comment]
I have no files in the library.
How can I create a new library? from the interface I also have this error message on the library tab.
I followed the installation procedure for Non-technical Users
thanks for the help

**Comment by akmzero** [comment]
> it's ok now but i have the problem loading local files but works for youtube

I think Local Files are still an issue, can you verify you have these packages installed?  I needed to install all of them on a fresh copy of 22.04LTS to get it to function.

ffmpeg 
python3
python3-pip 
python3.10-venv 
python3-dotenv

**Comment by pise77** [comment]
I had the same problem, I uninstalled the package, updated pip, installed python 3.10, reinstalled it, and it worked. and I wish the update had a language auto.

**Comment by alexschmitt54** [comment]
No problem it works now
Thanks
